### ISSUE TITLE
Pending page while we are not connected to metamask

### ISSUE THREAD

**Issue by Nebulis** [OpenCerts/admin-website-v2#32]
![image](https://user-images.githubusercontent.com/503185/124423545-f5e29700-dd97-11eb-8884-679c1e9f0a37.png)

This is how the page looks like. I think it would be better to hide part of the page or show a something that tells the user we wait for metamask to connect.

Let me know if not doable

**Comment by ChenRen93** [comment]
I have removed the auto calling of Metamask extension when the page load. The current method is constantly polling the Metamask, this may slow down the loading time or cause some issues in the long run. So instead of automatically request the Metamask extension, the user can connect using the Connect Metamask button at the upper right corner

**Comment by Nebulis** [comment]
I don't understand how it's related to my comment? My message is about the page that is displayed as long as a user is not connected
